apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifctoolkit

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ifctoolkit

  template:
    metadata:
      labels:
        app: ifctoolkit

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: ifctoolkit
          image: ghcr.io/colinbed/ifctoolkit:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: APP_URL
              value: "https://ifctoolkit.com"

            - name: FILE_RETENTION_MINUTES
              value: "30"

            - name: TMPDIR
              value: "/tmp"

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "4Gi"
            limits:
              memory: "4Gi"
              cpu: "2"
              ephemeral-storage: "12Gi"

          volumeMounts:
            - name: temporary-processing
              mountPath: /tmp

      volumes:
        - name: temporary-processing
          emptyDir:
            sizeLimit: "10Gi"
